<?php

namespace AppBundle\Repository;

/**
 * PropertiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertiesRepository extends \Doctrine\ORM\EntityRepository
{
}
